### ISSUE TITLE
Readme.md: `dependencies` shoulds contain `structmap-derive`

### ISSUE THREAD

**Issue by nsfoxer** [ex0dus-0x/structmap#6]
Missing `structmap-derive` dependency in section `Usage` of the `Readme.md` file .
```toml
[dependencies]
structmap = "0.1"
structmap-derive = "0.1.5"
```
